// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgresql://warpion_user:646DjTUMEds7rBZGsIJ2RcXYuqrAauBJ@dpg-d7u8nclckfvc73eohdf0-a.oregon-postgres.render.com/warpion"],
  },
});
